spring.application.name=board-back
server.port=4000
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@practice_high?TNS_ADMIN=D:\Develop\sqldeveloper\Wallet_PRACTICE
spring.datasource.username=developer
spring.datasource.password=Password1234

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB

